### ISSUE TITLE
How to change default charset?

### ISSUE THREAD

**Issue by evandroamparo** [mybatis/migrations#98] opened 2017-10-25 12:50 UTC
In my development.properties `script_char_set` is set to Windows-1252 but all the files generated by `migrate new` are encoded with UTF-8.
Does this setting affect only the reading of scripts during migrations or it should be used to generate new scripts too?
Is 'Windows-1252' correct?

**Comment by h3adache** [comment] 2017-10-25 16:53
Hi @evandroamparo you are correct, new doesn't actually do anything with the file encodings.
It simply copies the file [template_migration.sql](https://github.com/mybatis/migrations/blob/master/src/main/java/org/apache/ibatis/migration/template_migration.sql). We load the file content using the charset defined though. 
Is this causing an issue when you can't enter Windows-1252 encoded data into the files? Or causing issues reading from them after?

**Comment by evandroamparo** [comment] 2017-10-25 23:39
When the script has accented characters and the file is encoded with utf8, they are not translated correctly. I have to manually save each file with 1252 encoding.

**Comment by evandroamparo** [comment] 2017-10-25 23:47
My databases have Windows-1252 charset and don't accept data in utf-8

**Comment by h3adache** [comment] 2017-10-27 16:40
Interesting. What is the default encoding when you create a new file yourself @evandroamparo?
I will add a fix for this as soon as I have some time.
In the meantime, the only thing you actually need in the migration files is the
```
-- //@UNDO
```
That separates your migrate up and down commands.
I think we could/should probably remove the licensing from those templates as well.

**Comment by evandroamparo** [comment] 2017-10-27 17:03
I create files with Windows 1252 in Sublime Text, ANSI in Notepad.

**Comment by evandroamparo** [comment] 2017-10-27 17:06
+1 to remove the licensing

**Comment by harawata** [comment] 2017-10-27 18:11
@evandroamparo ,

A migration script generated by `migrate new` only uses ASCII characters unless you specify accented characters in the description (which probably is a bad idea because it will be part of the file name).
You just need to save the file in the right encoding after editing the script using accented characters, 
Sublime Text 3 has a menu 'Save with Encoding'.

Besides, script files must be written in the charset specified with `script_char_set`, but it does not have to be the same as the database character encoding.
If the data is not correctly inserted, it usually is a JDBC configuration problem.
Which database are you using?

For example, with MySQL, you may need to specify the database character encoding as part of JDBC URL.
```
jdbc:mysql://yourhost:3306/yourdb?characterEncoding=latin1
```

And +1 to remove licensing from the templates :)

**Comment by harawata** [comment] 2017-10-28 07:21
I might have not been clear enough.
Although it is technically possible for Migrations to save a new script in Windows-1252, it won't resolve your problem because the file will exactly be the same as the current one.

**Comment by h3adache** [comment] 2017-10-28 15:10
That’s a good point @harawata but I think there might be an issue in the encoding/decoding when you read utf-8 back to windows-1252. Can you create a quick example @evandroamparo?

**Comment by evandroamparo** [comment] 2017-10-28 23:53
I'm using Firebird and the URL already contains the enconding parameter:
`url=jdbc:firebirdsql:localhost/3050:test?encoding=WIN1252`
This is what I get when I save the script with UTF-8:
```
ID	NAME
-------------
1	JOÃƒO
```
And with Windows-1252 (expected):
```
ID	NAME
1	JOÃO
```

**Comment by harawata** [comment] 2017-10-29 06:30
@evandroamparo ,

That happens when your script is UTF-8 and `script_char_set` is Windows-1252 (or something similar) [1].
It should work if you set UTF-8 to `script_char_set`.
Note that JDBC connection URL still has to have `encoding=WIN1252`.
If it still does not work, please upload your migrations directory to your GitHub repo.

It works like...

- File (UTF-8) ->[InputStreamReader]-> Java (Unicode) -> [JDBC] -> DB (Windows 1252)

or

- File (Windows 1252) ->[InputStreamReader]-> Java (Unicode) -> [JDBC] -> DB (Windows 1252)

`script_char_set` is used when InputStreamReader reads the script.
In any case, it's all Unicode once the file is read in Java and the rest is up to JDBC.

[1] The code of `Ã` is `c3` in Windows-1252 and `c3 83` in UTF-8.
And in Windows-1252, the character mapped to `83` is `ƒ`.

**Comment by h3adache** [comment] 2018-01-02 18:26
@evandroamparo did @harawata's solution work for you?

**Comment by evandroamparo** [comment] 2018-12-06 14:06
> @evandroamparo did @harawata's solution work for you?

The only solution is to save the scripts with windows-1252. But if I forget to do this, worng data may be inserted.

**Comment by harawata** [comment] 2018-12-07 13:54
@evandroamparo ,

I have uploaded a simple test project : 
https://github.com/harawata/mybatis-migrations-issues/tree/master/gh-98
It does not include the driver. Download Jaybird 3.0.5 JDK 1.8 from [here](https://firebirdsql.org/en/jdbc-driver/) and copy `jaybird-full-3.0.5.jar` to the `driver` directory.

Note that:

- All scripts are saved in UTF-8
- `UTF8` is set to `script_char_set`
- JDBC connection URL includes `encoding=WIN1252`

Here is what I did to test:

1. Run firebird 3.0.4 using docker.

    ```sh
    $ docker run -d --rm --name firebird \
        -p 3050:3050 \
        -e ISC_PASSWORD=masterkey \
        jacobalberty/firebird:3.0.4
    ```

2. Login.

    ```sh
    $ docker exec -it firebird bash
    ```

3. Create a new user for the test and open isql.

    ```sh
    $ /usr/local/firebird/bin/gsec -user sysdba -pass masterkey -add test -pw test
    $ /usr/local/firebird/bin/isql
    ```

4. Create a test database with `WIN1252` as the default character set. Then exit.


    ```sql
    create database '/firebird/data/mybatis_migration.fdb' 
        user 'test' password 'test' 
        default character set WIN1252;
    exit;
    ```

5. Execute `migrate up` in the example project (Migrations version = 3.3.5, Java 11).
6. Verify the result. To avoid being confused by the console character set, `ascii_val` is used to verify the inserted data.

    ```sh
    $ /usr/local/firebird/bin/isql 127.0.0.1:/firebird/data/mybatis_migration.fdb -u test -p test
    ```
    ```sql
    select
        char_length(name) len,
        ascii_val(substring(name from 1 for 1)) chr1,
        ascii_val(substring(name from 2 for 1)) chr2,
        ascii_val(substring(name from 3 for 1)) chr3,
        ascii_val(substring(name from 4 for 1)) chr4
    from costumer;
    ```

Here is the result and it shows the data is correct : `JOÃO`.

```
         LEN    CHR1    CHR2    CHR3    CHR4 
============ ======= ======= ======= ======= 
           4      74      79     195      79 
```

And here is the result when `script_char_set=Windows-1252` is used. It shows that the first four characters are `JOÃƒ`.

```
         LEN    CHR1    CHR2    CHR3    CHR4 
============ ======= ======= ======= ======= 
           5      74      79     195     131 
```

So, it works as I explained.
Compare your project setup with this example and you may find the cause.

**Comment by harawata** [comment] 2018-12-10 13:14
Good! Thanks for letting us know the result! :D

**Closed by harawata** 2018-12-10 13:14 UTC
Labels: bug
