### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by sivasankarreddy0507** [mybatis/migrations#198] opened 2021-11-18 07:09 UTC
Trying to setup mybatis-migrations-3.3.9 on Solaris machine with java version "1.6.0_85". After using the command "migrate init " the below error is coming. Please assist in resolving the below issue. Please recommend the mybatis compatibile version for java 1.6 and 1.8 version. 

~/MyBatis/mybatis-migrations-3.3.9/mybatis_repo $ migrate init
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/ibatis/migration/Migrator : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: org.apache.ibatis.migration.Migrator.  Program will exit.

**Comment by harawata** [comment] 2021-11-18 07:26
Migrations 3.3.5 should work with Java 1.6.
https://github.com/mybatis/migrations/releases/tag/mybatis-migrations-3.3.5
mybatis-3.4.6 included in the zip archive also supports Java 1.6.

**Comment by sivasankarreddy0507** [comment] 2021-11-22 10:16
does mybatis-migrations support java version 1.4?if yes, which version should be used.

**Comment by harawata** [comment] 2021-11-22 12:42
Nope. There is no version that supports 1.4.

**Comment by harawata** [comment] 2021-11-22 19:29
You might be aware, but you can use Migrations from another machine if the DB server accepts JDBC connections.

I'll close this as it's not a bug report nor feature request.

**Closed by harawata** 2021-11-22 19:29 UTC
