### ISSUE TITLE
SQL Warning becomes exception becomes error and exit?

### ISSUE THREAD

**Issue by chb0github** [mybatis/migrations#89] opened 2017-10-11 23:54 UTC
```sql
========== Applying: 00045_DBA-3350_recreate_DHS_VendorReference.sql ===========
-- ========== ========== ========== ========== ========== ========== ==========
-- DB1
--
-- DBA-3350  DHS_VendorReference table creation
-- ========== ========== ========== ========== ========== ========== ==========
-- ---------- ---------- ----------
DROP TABLE IF EXISTS Company.DHS_VendorReference
```
```

Error executing: DROP TABLE IF EXISTS Company.DHS_VendorReference
.  Cause: java.sql.SQLWarning: Unknown table 'Company.DHS_VendorReference'
```

The whole point of a `DROP TABLE IF EXISTS` is specifically to make creating a table safe. 

I see the flag for `--force` but that forces all errors to continue. Frankly, this shouldn't even be a warning. The code very explicitly says it was an expected situation. How can I say "Ignore warnings" or "Don't treat warnings as errors"

**Comment by h3adache** [comment] 2017-10-12 00:54
Hi @chb0github this was just addressed by @harawata in #84 
Can you try that snapshot and see if that fixes it?
On a separate note, DROP TABLE IF EXISTS is a great feature but for migrations it's a strange syntax since you are already controlling what your schema looks like, so there shouldn't be a case where you need to 'guess' if a table exists.

**Comment by chb0github** [comment] 2017-10-12 03:56
I agree with you completely! Sadly, my situation is setting up an existing
database as coded infrastructure. You did inspire me on a solution but
still, it's supported by the underlying db so I would expect it to just
work.

Thanks for the patience

**Comment by chb0github** [comment] 2017-10-12 03:58
I just read the other ticket. I will try it tommorow from snapshot.

**Comment by chb0github** [comment] 2017-10-13 19:52
I tried `ignoreWarnings=true` in the properties file and `--ignoreWarnings` as a commandline option using the current checked in code. 

As a property: It does nothing
as an option `migrate up --ignoreWarnings`:

```
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant org.apache.ibatis.migration.options.Options.IGNOREWARNINGS
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.apache.ibatis.migration.options.Options.valueOf(Options.java:18)
	at org.apache.ibatis.migration.options.OptionsParser.parseOptions(OptionsParser.java:54)
	at org.apache.ibatis.migration.options.OptionsParser.parse(OptionsParser.java:31)
	at org.apache.ibatis.migration.CommandLine.execute(CommandLine.java:37)
	at org.apache.ibatis.migration.Migrator.main(Migrator.java:20)

```

current options enum:

```java
public enum Options {
  PATH, ENVPATH, SCRIPTPATH, DRIVERPATH, HOOKPATH, ENV, FORCE, TRACE, HELP, TEMPLATE, IDPATTERN
}

```

pom:

```xml
  <parent>
    <groupId>org.mybatis</groupId>
    <artifactId>mybatis-parent</artifactId>
    <version>29</version>
    <relativePath />
  </parent>

  <artifactId>mybatis-migrations</artifactId>
  <version>3.3.2-SNAPSHOT</version>
```

**Comment by chb0github** [comment] 2017-10-14 01:35
Nevermind, I looked at the code more and figured it out:

it's `ignore_warnings`

**Comment by harawata** [comment] 2017-10-16 18:48
Hi @chb0github ,

After discussion, we have decided to change the default value of `ignore_warnings` to `true`.
It means that SQL warnings will not stop migrations in 3.3.2 by default.
I am sorry if there is any confusion.

**Comment by chb0github** [comment] 2017-10-16 20:12
Thanks! Seems fair - and maybe warnings still go to stderr?

**Comment by harawata** [comment] 2017-10-24 17:18
It can be quite verbose, so I think it's not necessary.
Closing as a duplicate of #84 .

**Closed by harawata** 2017-10-24 17:18 UTC
