### ISSUE TITLE
Feature request : Disable the WARNING: Missing migration script. 

### ISSUE THREAD

**Issue by pkolodziejczyk** [mybatis/migrations#191] opened 2021-07-07 13:27 UTC
## MyBatis version
3.3.9

When doing a migrate status

Would like to have a way to disable this specific warning.

> WARNING: Missing migration script. 

I have search the documentation and the code. But, I haven't found the anything related.

**Comment by harawata** [comment] 2021-07-07 18:45
Hello @pkolodziejczyk ,

May I ask why?
There should be no missing script in any situation, I think.

**Comment by pkolodziejczyk** [comment] 2021-07-15 14:21
The current setup where I work :

Each version have a new git branch that include only the new script that will be released.

One data base that contains the history of past version.

When we release a version, we generate the scripts to pass in production. Then added the branch to the master branch.

So, when we are on a branch of a version. We only have the script of this version. It's allow use to have concurrent evolution (or group of evolution) on the same database. And only push or review one evolution (or group of evolution) a time.

Because, the script of the previous versions are missing.

This warning was added after the setup of workflow in the company. And, I would like to avoid using an earlier version just because of this warning.

**Comment by harawata** [comment] 2021-07-15 16:11
Hello @pkolodziejczyk ,

In that case, it seems to be the right/expected behavior to output the warning, I'm afraid.
As it is just a warning and does not make your migration fail, you should just ignore it.
Another workaround would be to add the `--quiet` option when executing the `migrate` command.

**Comment by pkolodziejczyk** [comment] 2021-07-16 12:53
Well a --quite  status return : 

>------------------------------------------------------------------------
>-- MyBatis Migrations - status
>------------------------------------------------------------------------
>------------------------------------------------------------------------
>-- MyBatis Migrations SUCCESS
>-- Total time: 4s
>-- Finished at: Fri Jul 16 14:46:43 CEST 2021
>-- Final Memory: 21M/500M
>------------------------------------------------------------------------

So the status command become useless.

And the desired outcome is : 
>------------------------------------------------------------------------
>-- MyBatis Migrations - status
>------------------------------------------------------------------------
>20210630092025 2021-06-30 10:22:04 pko SIS2 SISTEMA-19909 Error while generating NTME documents - Unsupported characters
>20210701151916 2021-07-01 17:29:34 jgt CONT CONTRATS-18809 Projet Autonomie indicateurs de pilotage <=== MISSING!
>20210716134254    ...pending...    pko SIS2 SISTEMA-21801 Codification - Ajout ID tache dans la table SIN DON MED VICTIME
>------------------------------------------------------------------------
>-- MyBatis Migrations SUCCESS
>-- Total time: 4s
>-- Finished at: Fri Jul 16 14:45:56 CEST 2021
>-- Final Memory: 21M/500M
>------------------------------------------------------------------------


without :  

>WARNING: Missing migration script. id='20210701151916', description=' jgt CONT CONTRATS-18809 Projet Autonomie indicateurs de pilotage'.

If --quite could be change for status to have a useful behaviour. It's okay for me to have those warning in standard.

**Comment by harawata** [comment] 2021-07-17 07:26
> If --quite could be change for status to have a useful behaviour. It's okay for me to have those warning in standard.

Although it might be useful to you, it makes it `--quiet` option useless.
As I mentioned, the warning does not change the result of your migration, so you should be able to ignore it safely.

**Comment by harawata** [comment] 2021-12-08 17:37
Closing as won't fix.
Hope my explanation was satisfactory.

**Closed by harawata** 2021-12-08 17:37 UTC
